" .vimrc

" Vim 8 defaults
unlet! skip_defaults_vim
silent! source $VIMRUNTIME/defaults.vim

" Plugin SETTINGS
call plug#begin('~/.vim/plugged')

Plug 'scrooloose/nerdtree'
Plug 'bling/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'jiangmiao/auto-pairs'
Plug 'junegunn/goyo.vim'

" Colors
Plug 'tomasiser/vim-code-dark'

call plug#end()

" Color SETTINGS
set t_Co=256
set t_ut=
colorscheme codedark
let g:airline_theme = 'codedark'

" BASIC SETTINGS

let mapleader       =','
let maplocalleader  =','

filetype plugin on
filetype indent on
set nocompatible
syntax enable
set path+=**
set wildmenu
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set number
set autoindent
set cindent
set showmatch
set incsearch
set hlsearch
set cursorline
set laststatus=2
set backspace=indent,eol,start
set encoding=utf-8
set mouse=a

" MAPPINGS

" Open new line below and above current line
nnoremap <leader>o o<ESC>
nnoremap <leader>O O<ESC>

" Enhanced keyboard mappings
"
" in normal mode F2 will save the file
nmap <F2> :w<CR>
" in insert mode F2 will exit insert, save, enters insert again
imap <F2> <ESC>:w<CR>i
" in normal mode F3 will save and exit the file
nmap <F3> :wq<CR>
" in insert mode F3 will exit insert, save and exit
imap <F3> <ESC>:wq<CR>

" Goyo
nmap <F4> :Goyo<CR>

" NERDTree Toggle
nmap <F5> :NERDTreeToggle<CR>

" vim-plug settings
nmap <F6> :PlugInstall<CR>
nmap <F7> :PlugUpdate<CR>
nmap <F8> :PlugClean<CR>
nmap <F9> :PlugUpgrade<CR>

" vim-airline settings
let g:airline#extensions#tabline#enabled = 1
